### ISSUE TITLE
1.21 lost the bugtracker information

### ISSUE THREAD

**Issue by eserte** [catalyst/Authen-NZRealMe#8]
The META.* files in 1.21 do not list anymore the bugtracker information: https://metacpan.org/diff/file?target=AJM/Authen-NZRealMe-1.21/&source=GRANTM%2FAuthen-NZRealMe-1.20#META.json
So MetaCPAN now again links to rt.cpan.org.
I assume this change was not intended, as rt.cpan.org will be closed soon...

**Comment by andrewjmaguire** [comment]
Fixed in v1.22
